# Generated by Django 3.1.5 on 2021-02-15 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_auto_20210215_2120'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='text_preview',
        ),
        migrations.AddField(
            model_name='notification',
            name='preview_text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
