# Generated by Django 3.1.5 on 2021-02-17 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_auto_20210217_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='preview_text',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
