# Generated by Django 3.1.5 on 2021-02-05 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='message',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
