# Generated by Django 3.1.5 on 2021-02-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moderation', '0002_report_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='reason',
            field=models.IntegerField(choices=[(0, 'Rude or vulgar'), (1, 'Spam'), (2, 'Copyright issue'), (3, 'Harassment or hate speech'), (4, 'Inappropriate content'), (5, 'Other')], default=5),
            preserve_default=False,
        ),
    ]
