# Generated by Django 3.1.5 on 2021-02-11 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0003_tag_followers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='followers',
            field=models.ManyToManyField(blank=True, null=True, related_name='followed_tags', to=settings.AUTH_USER_MODEL),
        ),
    ]
