# Generated by Django 3.1.5 on 2021-02-11 13:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articles', '0004_auto_20210211_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='followed_tags', to=settings.AUTH_USER_MODEL),
        ),
    ]
