# Generated by Django 3.1.7 on 2021-02-28 21:53

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_is_moderator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from='username', unique=True),
        ),
    ]
