# Generated by Django 3.1.5 on 2021-01-30 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20210130_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, default='uploads/avatars/default_avatar.png', null=True, upload_to='uploads/avatars'),
        ),
    ]
