# Generated by Django 3.1.5 on 2021-01-30 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20210130_0015'),
        ('users', '0006_auto_20210130_2349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='uploads/avatars/default_avatar.png', upload_to='uploads/avatars'),
        ),
        migrations.AlterField(
            model_name='user',
            name='saved_articles',
            field=models.ManyToManyField(blank=True, null=True, related_name='saves', to='articles.Article'),
        ),
    ]
